### ISSUE TITLE
导致页面样式错误，injected stylesheet注入导致页面显示问题

### ISSUE THREAD

**Issue by daidaibg** [zxlie/FeHelper#200]
injected stylesheet注入导致页面显示问题
![image](https://user-images.githubusercontent.com/55817318/209641494-c2578ab9-73d1-49aa-9fcc-65c6e4876a65.png)

**Comment by zxlie** [comment]
已提交版本审核，预计明天或者后天就通过了；影响日常使用的话，可以暂时禁用FH

**Comment by chenshi1324** [comment]
我刚想发iss来着 我还以为是网站问题

**Comment by frei-x** [comment]
简单的 className 别乱用....  不管啥样式都得加上自己特有前缀

**Comment by syq2930644833** [comment]
我刚想发iss来着 我还以为是网站问题

**Comment by zyyv** [comment]
+1 呀，还会注入
```css
[hidden] { 
  display: none !important; // 这个 important 很致命呀
}
```
