### ISSUE TITLE
注入全局样式导致污染

### ISSUE THREAD

**Issue by nemobb** [zxlie/FeHelper#203]
请不要全局注入这样的样式，会污染其他的信息。
```css
item {
    display: block;
    padding-left: 20px;
    margin-left: -20px;
    position: relative;
    padding-top: 1px;
    padding-bottom: 1px;
}
```
